name: Pajarraco Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Pajarraco-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: npm install;
      - run: npm start;
